const FEES_FOR_GET_INPUTS = 1400;
const FEES_FOR_CREATE_CHANNEL = 500;
const FEES_FOR_CHANNEL_OPERATIONS = 1000;

exports.FEES_FOR_GET_INPUTS = FEES_FOR_GET_INPUTS;
exports.FEES_FOR_CREATE_CHANNEL = FEES_FOR_CREATE_CHANNEL;
exports.FEES_FOR_CHANNEL_OPERATIONS = FEES_FOR_CHANNEL_OPERATIONS;